### ISSUE TITLE
Uncaught TypeError: Cannot read property 'path' of null

### ISSUE THREAD

**Issue by kimgospel** [legofneb/atom-tfs-auto#1]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Mac OS X 10.11.2
**Thrown From**: [atom-tfs-auto](https://github.com/legofneb/atom-tfs-auto) package, v0.2.0

### Stack Trace

Uncaught TypeError: Cannot read property 'path' of null

```
At /Users/Gospel/.atom/packages/atom-tfs-auto/lib/atom-tfs-auto.coffee:15

TypeError: Cannot read property 'path' of null
    at /Users/Gospel/.atom/packages/atom-tfs-auto/lib/atom-tfs-auto.coffee:15:12
    at Emitter.module.exports.Emitter.emit (/Users/Gospel/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at /Users/Gospel/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1314:25
```

### Commands

```
  3x -0:12.2.0 editor:newline (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-tfs-auto, v0.2.0
auto-encoding, v0.5.0
auto-id-class, v0.2.6
auto-indent, v0.5.0

# Dev
No dev packages
```

**Comment by kwiss** [comment]
+1

**Comment by legofneb** [comment]
This package only works with Windows right now. I haven't looked into it, but is there interest in a Mac OS X version?

**Comment by mvhoute** [comment]
I certainly have interest in a Mac OSX version! If you need someone to debug or test your package on a OSX machine, don't hesitate to contact me.

**Comment by rshackleton-netc** [comment]
Receiving this error on Windows 7 (Atom v1.4.0, atom-tfs-auto v0.2.0). The error happens when opening or editing a new file which has not been saved to the file system.

**Comment by legofneb** [comment]
@rshackleton-netc - this seems to be a separate issue than the OS X stuff, so I have created a new issue, #2  to fix it. I don't think it will take me long to resolve it.

**Comment by Cr4ck3rs** [comment]
Having this issue on windows:
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Unknown Windows Version
**Thrown From**: [atom-tfs-auto](https://github.com/legofneb/atom-tfs-auto) package, v0.2.0


### Stack Trace

Uncaught TypeError: Cannot read property 'path' of null

```
At /C:/Users/jaguero/.atom/packages/atom-tfs-auto/lib/atom-tfs-auto.coffee:17

TypeError: Cannot read property 'path' of null
    at file:///C:/Users/jaguero/.atom/packages/atom-tfs-auto/lib/atom-tfs-auto.coffee:15:12
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\jaguero\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\jaguero\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at C:\Users\jaguero\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1378:25
```

### Commands

```
     -4:02.2.0 gibber:toggle (atom-text-editor.editor.power-mode.is-focused)
  2x -3:51.7.0 core:backspace (atom-text-editor.editor.power-mode.is-focused)
     -3:03.8.0 pane:split-right (div.package-detail.panels-item)
  6x -3:00.1.0 application:new-file (ul.list-inline.tab-bar.inset-panel)
  2x -2:45.5.0 pane:split-down (atom-text-editor.editor.power-mode)
  2x -2:37.3.0 pane:close (ul.list-inline.tab-bar.inset-panel)
     -2:21.2.0 atom-terminal-panel:toggle-autocompletion (atom-text-editor.editor.power-mode.is-focused)
     -2:21.1.0 editor:move-to-beginning-of-word (atom-text-editor.editor.power-mode.is-focused)
     -2:20.7.0 core:move-right (atom-text-editor.editor.power-mode.is-focused)
     -2:20.4.0 core:select-left (atom-text-editor.editor.power-mode.is-focused)
     -2:19.1.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.power-mode.is-focused)
     -1:46.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:26.7.0 core:move-left (atom-text-editor.editor.power-mode.is-focused)
     -1:26.4.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.power-mode.is-focused)
     -1:17 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:51.2.0 core:move-left (atom-text-editor.editor.power-mode.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "angularjs-helper",
      "atom-react-native-autocomplete",
      "gulp-control",
      "imdone-atom",
      "json-schema",
      "clipboard-plus",
      "autocomplete-json",
      "linter-sass-lint",
      "autocomplete-python",
      "linter-pylint",
      "easy-motion-redux",
      "autoclose-html",
      "autocomplete-html",
      "autocomplete-html-entities",
      "language-gfm",
      "linter-eslint",
      "package-sync-plus",
      "linter-csslint",
      "turbo-javascript",
      "react",
      "atom-tfs-auto",
      "atom-tfs"
    ],
    "openEmptyEditorOnStart": false,
    "themes": [
      "steam-pirate-ui",
      "monokai-slate"
    ]
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.7.0
advanced-open-file, vundefined
angular-2-typeScript-snippets, v0.4.6
angularjs, v0.3.4
atom-html-preview, v0.1.21
atom-jasmine, v0.8.1
atom-pair, v2.0.10
atom-terminal-panel, v4.4.4
atom-ternjs, v0.14.2
atom-typescript, v10.0.0
atom-wallaby, v1.0.8
atom-yeoman, v0.3.15
autocomplete-angular-material, v0.4.0
autocomplete-js-import, v1.0.1
autocomplete-paths, v1.0.2
build, v0.65.0
busy, v0.5.0
clean-context-menu, v0.3.1
docblock-format-helper, v0.3.0
docblockr, v0.7.3
editorconfig, v1.4.1
emmet, v2.4.3
fast-eslint, v2.15.1
file-icons, v1.7.16
fold-functions, v0.4.3
gibber, v0.1.3
git-diff-details, v1.3.0
git-log, v0.4.1
glowing-cursor, v0.1.1
highlight-selected, v0.11.2
javascript-snippets, v1.2.1
js-hyperclick, v1.4.2
language-asp-html, v0.2.0
language-aspx, v0.4.0
language-babel, v2.31.0
language-cshtml, v0.2.1
language-gitignore, v0.2.0
language-javascript-jsx, v0.3.7
language-markdown, v0.15.0
language-tsql, v0.19.0
language-TSQL-2012, v0.3.0
language-vb, v0.1.0-pre1
less-than-slash, v0.13.0
linter, v1.11.14
linter-coffeelint, v1.1.2
linter-htmlhint, v1.2.1
linter-jshint, v2.1.0
linter-markdown, v1.5.2
linter-stylelint, v2.17.0
linter-xo, v0.16.0
markdown-preview-enhanced, v0.7.5
merge-conflicts, v1.4.4
minimap, v4.24.7
minimap-bookmarks, v0.3.1
minimap-codeglance, v0.4.5
minimap-find-and-replace, v4.5.1
minimap-git-diff, v4.3.1
minimap-highlight-selected, v4.4.0
minimap-linter, v1.1.1
minimap-pigments, v0.2.1
minimap-selection, v4.4.0
monokai-slate, v0.5.0
motepair, v0.21.0
neon-selection, v0.3.2
node-debugger, v1.7.0
omnisharp-atom, v0.30.4
open-recent, v5.0.0
package-switch, v0.5.0
pigments, v0.31.1
project-manager, v2.9.7
regex-railroad-diagram, v0.16.0
rest-client, v1.2.0
save-session, v0.16.0
steam-pirate-ui, v0.6.1
symbols-tree-view, v0.13.2
sync-settings, v0.7.2
tool-bar, v1.0.0
tool-bar-almighty, v0.6.1
tree-view-git-branch, v0.1.2
tree-view-git-status, v1.0.1
useful-context-menu, v0.6.0
yuno-commit-plus, v0.2.1

# Dev
No dev packages
```

**Comment by legofneb** [comment]
I've published a new package with the null guard, please let me know if this is still an issue

**Comment by m1ga** [comment]
@legofneb have interest in an osx version, too!
